version: '2.1'

services:
    hostapd:
        privileged: true
        image: 'gasket/portal'
        build:
            context: '.'
            dockerfile: './Dockerfile.hostapd'
        volumes:
            - './docker-compose/hostapd/:/etc/hostapd'
        command:  bash -c "until ip link show eth3; do sleep 1; done;
            ip link set eth3 down;
            ip link set eth3 address 44:44:44:44:44:44;
            ip link set eth3 up;
            ping 10.0.0.40 -c5;
            hostapd -ddt /etc/hostapd/wired.conf"
        ports:
            - "8892:8892/udp"
        networks:
            controller-portal-net:
                ipv4_address: 172.220.0.101
            radius-net:
                ipv4_address: 172.221.0.101
        sysctls:
        - net.ipv4.conf.all.send_redirects=0
        - net.ipv4.ip_forward=0

    faucet:
        image: 'faucet/faucet'

        volumes:
            - '/var/log/faucet:/var/log/faucet'
            - '/etc/faucet:/etc/faucet'

        ports:
            - '6653:6653'
            - '9302'
        environment:
            FAUCET_CONFIG_STAT_RELOAD: '${FAUCET_CONFIG_STAT_RELOAD}'
            FAUCET_EVENT_SOCK: '${FAUCET_EVENT_SOCK}'
        networks:
            control-plane-net:
                ipv4_address: 172.222.0.103

    gasket:
        build:
            context: '.'
            dockerfile: './Dockerfile.auth'
        volumes:
            - '/var/log/faucet:/var/log/faucet'
            - '/etc/faucet:/etc/faucet'
            - '/var/run/:/var/run/'
        networks:
            control-plane-net:
                ipv4_address: 172.222.0.100
            controller-portal-net:
                ipv4_address: 172.220.0.100

    freeradius:
        build:
            context: '.'
            dockerfile: './Dockerfile.freeradius'
        volumes:
            - "./docker-compose/freeradius/raddb/clients.conf:/etc/freeradius/clients.conf"
            - "./docker-compose/freeradius/raddb/users:/etc/freeradius/users"
            - "./docker-compose/freeradius/raddb/dictionary:/etc/freeradius/dictionary"
            - "./docker-compose/freeradius/log/radius-log:/var/log/radius/"
        networks:
            radius-net:
                ipv4_address: 172.221.0.102

    rabbitmq_adapter:
        restart: always
        depends_on:
            - faucet
        image: 'faucet/faucet-event-adapter-rabbitmq'
        volumes_from:
            - faucet
        environment:
            FAUCET_EVENT_SOCK: '${FAUCET_EVENT_SOCK}'
            FA_RABBIT_HOST: '${FA_RABBIT_HOST}'
            FA_RABBIT_PORT: '${FA_RABBIT_PORT}'
            FA_RABBIT_EXCHANGE: '${FA_RABBIT_EXCHANGE}'
            FA_RABBIT_EXCHANGE_TYPE: '${FA_RABBIT_EXCHANGE_TYPE}'
            FA_RABBIT_ROUTING_KEY: '${FA_RABBIT_ROUTING_KEY}'
        networks:
            control-plane-net:
                ipv4_address: 172.222.0.105


    rabbitmq_server:
        restart: always
        image: 'rabbitmq:3-management'
        networks:
            control-plane-net:
                ipv4_address: 172.222.0.104

        ports:
            - "5672:5672"

networks:
    control-plane-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.222.0.0/24

    controller-portal-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.220.0.0/24
    radius-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.221.0.0/24
