name: Periodic tests

on:
  schedule:
    # NZST = UTC + 12
    # Schedule to run at midnight & lunch-time
    - cron: '0 0,12 * * *'

env:
  FAUCET_TEST_IMG: "c65sdn/tests"
  SHARDARGS: "--privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 --ulimit core=99999999999:99999999999 -v /var/local/lib/docker:/var/lib/docker -v /var/tmp:/var/tmp"

jobs:
  generative-testing:
    name: Generative tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        MATRIX_SHARD: [--generative_unit, --generative_tolerance]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup docker test requirements
        run: |
          ulimit -c unlimited
          echo '/var/tmp/core.%h.%e.%t' | sudo tee /proc/sys/kernel/core_pattern
          sudo modprobe openvswitch
          sudo modprobe ebtables
      - name: Build docker
        run: docker build --pull -t ${FAUCET_TEST_IMG} -f Dockerfile.tests . || exit 1
      - name: Run docker
        run: sudo docker run ${SHARDARGS} -e FAUCET_TESTS="${{ matrix.MATRIX_SHARD }}" -e FAUCET_GENERATIVE_LIMIT=200 -t ${FAUCET_TEST_IMG} || exit 1
      - name: Detect core dumps
        run: if [ ls -1 /var/tmp/core* > /dev/null 2>&1 ]; then exit 1; fi
