name: Build debian packages for release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  debian-package:
    name: "Build debian packages"
    runs-on: ubuntu-latest
    environment:
      name: "release"
    container:
      image: "debian:latest"
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y upgrade
          apt-get -y install devscripts dpkg-dev debhelper equivs
      - name: Enable faucet apt repo
        run: |
          echo "deb https://packagecloud.io/faucetsdn/faucet/$(lsb_release -si | awk '{print tolower($0)}')/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/faucet.list
          curl -1sLf https://packagecloud.io/faucetsdn/faucet/gpgkey -o /etc/apt/trusted.gpg.d/faucet.asc
          apt-get update
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Bump version
        run: |
          export DEBEMAIL='maintainers@faucet.nz'
          export DEBFULLNAME='Faucet Maintainers'
          debchange --newversion "${GITHUB_REF_NAME}" -b "New upstream release"
      - name: Build package
        run: |
          mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
          dpkg-buildpackage -b -us -uc -rfakeroot
      - name: Store package
        run: |
          mkdir -p packages/all
          cp ../*.deb packages/all
      - name: Publish package on packagecloud
        uses: faucetsdn/action-packagecloud-upload-debian-packages@v1
        with:
          path: packages/
          repo: faucetsdn/faucet
          token: ${{ secrets.PACKAGECLOUD_TOKEN }}
