name: Build python packages for release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  RELEASE_PY_VER: "3.12"

jobs:
  python-package:
    name: "Build and publish python packages"
    runs-on: ubuntu-latest
    environment:
      name: "release"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up python-${{ env.RELEASE_PY_VER }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.RELEASE_PY_VER }}
      - name: Build python package
        run: |
          pip3 install setuptools
          python3 setup.py sdist
      - name: Publish python package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
